# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50 
  
# Position Controllers ---------------------------------------
lower_arm_position_controller:
  type: effort_controllers/JointPositionController
  joint: lower_arm_joint
  pid: {p: 250.0, i: 0.01, d: 10.0}

upper_arm_position_controller:
  type: effort_controllers/JointPositionController
  joint: upper_arm_joint
  pid: {p: 250.0, i: 0.01, d: 10.0}