<?xml version="1.0" ?>
<robot name="tarm" xmlns:xacro="http://ros.org/wiki/xacro">

	<xacro:include filename="$(find tarm_description)/urdf/materials.xacro"/>
	<xacro:include filename="$(find tarm_description)/urdf/tarm.gazebo.xacro"/>
	<xacro:include filename="$(find tarm_description)/urdf/tarm.transmission.xacro"/>

	<!-- Properties -->
    <xacro:property name="PI" value="3.1415926535897931"/>
	<xacro:property name="upper_length" value="0.5"/>
	<xacro:property name="lower_length" value="0.8"/>
	<xacro:property name="arm_width" value="0.05"/>
	<xacro:property name="upper_mass" value="1.0"/>
	<xacro:property name="lower_mass" value="1.0"/>
	<!-- Base -->
	<xacro:property name="base_length" value="1.5"/>
	<xacro:property name="base_width" value="0.08"/>
	<xacro:property name="base_mass" value="2.5"/>


	<!-- Used for fixing robot to Gazebo 'base_link' -->
	<link name="world"/>

	<joint name="fixed" type="fixed">
		<parent link="world"/>
		<child link="base_link"/>
	</joint>

	<link name="base_link">
		<visual>
			<origin xyz="0 0 ${base_length/2}" rpy="0 0 0"/>
			<geometry>
	         	<box size="${base_width} ${base_width} ${base_length}"/>
	      	</geometry>
			<material name="light_black"/>
		</visual>

		<collision>
			<origin xyz="0 0 ${base_length/2}" rpy="0 0 0"/>
			<geometry>
	         	<box size="${base_width} ${base_width} ${base_length}"/>
	      	</geometry>
			<material name="light_black"/>
		</collision>

		<inertial>
			<origin xyz="0 0 ${base_length/2}" rpy="0 0 0"/>
			<mass value="${base_mass}"/>
			<inertia ixx="0.1" ixy="0.0" ixz="0.0"
					iyy="0.1" iyz="0.0"
					izz="0.1" />
		</inertial>
	</link>


	<!-- Lower Arm Joint -->
	<joint name="lower_arm_joint" type="revolute">
		<parent link="base_link"/>
		<child link="lower_arm_link"/>
		<origin xyz="0.0 -${base_width} ${base_length}" rpy="${PI/2} 0 0"/>
		<axis xyz="0 0 1"/>
		<limit effort="1000.0" lower="-2.0" upper="2.0" velocity="0.5"/>
	</joint>

	<!-- Lower Arm Link -->
	<link name="lower_arm_link">
		<visual>
			<origin xyz="${lower_length/2} 0 0" rpy="0 0 0"/>
			<geometry>
	         	<box size="${lower_length} ${arm_width} ${arm_width}"/>
	      	</geometry>
			<material name="orange"/>
		</visual>

		<collision>
			<origin xyz="${lower_length/2} 0 0" rpy="0 0 0"/>
			<geometry>
	         	<box size="${lower_length} ${arm_width} ${arm_width}"/>
	      	</geometry>
			<material name="orange"/>
		</collision>

		<inertial>
			<origin xyz="${lower_length/2} 0 0" rpy="0 0 0"/>
			<mass value="${lower_mass}"/>
			<inertia ixx="0.1" ixy="0.0" ixz="0.0"
					iyy="0.1" iyz="0.0"
					izz="0.1" />
		</inertial>

	</link>


	<!-- Upper Arm Joint -->
	<joint name="upper_arm_joint" type="revolute">
		<parent link="lower_arm_link"/>
		<child link="upper_arm_link"/>
		<origin xyz="${lower_length - arm_width/2} 0 ${arm_width}" rpy="0 0 0"/>
		<axis xyz="0 0 1"/>
		<limit effort="1000.0" lower="-2.0" upper="2.0" velocity="0.5"/>
	</joint>

	<!-- Upper Arm Link -->
	<link name="upper_arm_link">
		<visual>
			<origin xyz="${upper_length/2} 0 0" rpy="0 0 0"/>
			<geometry>
	         	<box size="${upper_length} ${arm_width} ${arm_width}"/>
	      	</geometry>
			<material name="dark"/>
		</visual>

		<collision>
			<origin xyz="${upper_length/2} 0 0" rpy="0 0 0"/>
			<geometry>
	         	<box size="${upper_length} ${arm_width} ${arm_width}"/>
	      	</geometry>
			<material name="dark"/>
		</collision>

		<inertial>
			<origin xyz="${upper_length/2} 0 0" rpy="0 0 0"/>
			<mass value="${upper_mass}"/>
			<inertia ixx="0.1" ixy="0.0" ixz="0.0"
					iyy="0.1" iyz="0.0"
					izz="0.1" />
		</inertial>

	</link>

</robot>
